### PR TITLE
Remove unused functions

### PR DESCRIPTION
**Pull request by uis246**

### CODE REVIEW

**Comment by uis246** [comment]
Sorry for previous bullshit PR

**Comment by uis246** [comment]
This is more fitting name

**Comment by tkoeppe** [comment]
You're not really just "removing" things, are you? More like "replace strlwr with strlower"?

**Comment by uis246** [comment]
> You're not really just "removing" things, are you? More like "replace strlwr with strlower"?

Removing in two places and replacing in one. Yeah, still not most fitting name.

**Comment by uis246** [comment]
> You're not really just "removing" things, are you? More like "replace strlwr with strlower"?

In aselib it was just removed.

**Pull request merged**
