### PR TITLE
Angle arrow for entities with angle and fixed size

### PR DESCRIPTION
**Pull request by Pan7**

### CODE REVIEW

**Comment by ensiform** [comment]
You should only check for fixedsize not the angle key.  Not all ents contain the angle key being set. IE implied 0.  I've also seen a few cases where it does not render still though.  Dunno why.

**Comment by Pan7** [comment]
How to know it should have an arrow if it has no angle key?

**Comment by Mateos81** [comment]
The default then (0), so you see where it points by default, and thus on all cases, may the key be set or not.

**Comment by ensiform** [comment]
Any entity that is fixed size can show the arrow. At "0" as mentioned.  This is 1.5 style I believe?

**Comment by Pan7** [comment]
Its better to add the angle key for each entity that is missing it in the def files.

**Pull request merged**
