### PR TITLE
[q3map2] add basic etlegacy support to q3map2

### PR DESCRIPTION
**Pull request by illwieckz**
- add basic etlegacy support to q3map2

To provide complete support, q3map2 must be extended to specify multiple basepath for the same game since q3map2 extends the “etmain” basepath with its own “legacy” basepath, see #358

### CODE REVIEW

**Comment by illwieckz** [comment]
See [xonotic/netradiant!34](https://gitlab.com/xonotic/netradiant/merge_requests/34) for netradiant's counterpart.

**Comment by TTimo** [comment]
What's the status of this. Don't we need a gamepack? The editor still needs to distinguish running in vanilla ET vs ETL mode.

**Comment by ensiform** [comment]
What is the point of this?  ET:L has no real differences over ET.  A better fix would  be to allow all games to support custom engine binaries (defaulting to the original) and allow custom homepath support on Linux.

**Comment by Mateos81** [comment]
Yet there's no differences, but it will probably have new entities in the future. ^^'
Talking about ET and entities, #379 is still opened, @merlin1991.

**Comment by ensiform** [comment]
I still don't see how adding new entities requires an entire new `"-game"` flag for q3map2 specifically.

**Comment by Mateos81** [comment]
Well, each game has its gamepack, I thought that would matter for Radiant during profile initialization

**Comment by ensiform** [comment]
@Mateos81, you can supply ent def files with mods though too, so its not a big deal.  Plus its not like an ent def is needed to place an entity?

**Comment by TTimo** [comment]
Continue this on a bug instead of a pull request if there is a need.

**Pull request closed without merging**
