### PR TITLE
Fix crash upon loading an OBJ model

### LINKED ISSUE #395: Picomodel crash when loading valid .obj model
There's a crash in the PicoModel loading valid .obj models. Here is the error:

```
radiant.bin(58676,0x7fffb2b753c0) malloc: *** error for object 0x7fcde79b0400: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

And here is the backtrace:

```
(lldb) bt
* thread #1: tid = 0x6070cd, 0x00007fffa9e56dd6 libsystem_kernel.dylib`__pthread_kill + 10, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fffa9e56dd6 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fffa9f42787 libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fffa9dbc420 libsystem_c.dylib`abort + 129
    frame #3: 0x00007fffa9eac03f libsystem_malloc.dylib`free + 530
    frame #4: 0x000000011076d055 vfspk3.so`vfsFreeFile(p=0x00007fa8484a8000) + 21 at vfs.cpp:513
  * frame #5: 0x00000001105bfc64 model.so`PicoFreeFileFunc(file=0x00007fa8484a8000) + 36 at plugin.cpp:95
    frame #6: 0x0000000110598165 model.so`_pico_free_file(buffer=0x00007fa8484a8000) + 69 at picointernal.c:234
    frame #7: 0x000000011059b460 model.so`PicoLoadModel(fileName="models/weapons/machinegun/tris.obj", frameNum=0) + 304 at picomodel.c:244
    frame #8: 0x00000001105bdc5f model.so`CPicoModel::load(this=0x00007fa849674830, name="models/weapons/machinegun/tris.obj", frame=0) + 95 at cpicomodel.cpp:55
    frame #9: 0x00000001105bdb66 model.so`CPicoModel::CPicoModel(this=0x00007fa849674830, key=0x00007fff51a9b5a8) + 118 at cpicomodel.cpp:27
    frame #10: 0x00000001105bdead model.so`CPicoModel::CPicoModel(this=0x00007fa849674830, key=0x00007fff51a9b5a8) + 29 at cpicomodel.cpp:26
    frame #11: 0x00000001105c6071 model.so`cache_element<std::__1::pair<Str, int>, CPicoModel>::construct(this=0x00007fa84ea81520, key=0x00007fff51a9b5a8) + 65 at remap.cpp:61
    frame #12: 0x00000001105c3d45 model.so`cache_element<std::__1::pair<Str, int>, CPicoModel>::capture(this=0x00007fa84ea81520, key=0x00007fff51a9b5a8) + 53 at remap.cpp:43
    frame #13: 0x00000001105c1bc9 model.so`ModelCache::capture(this=0x00000001105d03b0, key=0x00007fff51a9b5a8) + 41 at remap.cpp:81
    frame #14: 0x00000001105c883e model.so`ModelWrapper::ModelWrapper(this=0x00007fa8496fc030, model=0x00007fa8496407f0, name="models/weapons/machinegun/tris.obj") + 302 at remap.cpp:280
    frame #15: 0x00000001105c0b65 model.so`ModelWrapper::ModelWrapper(this=0x00007fa8496fc030, model=0x00007fa8496407f0, name="models/weapons/machinegun/tris.obj") + 37 at remap.cpp:279
    frame #16: 0x00000001105c0ac4 model.so`LoadModel(model=0x00007fa8496407f0, name="models/weapons/machinegun/tris.obj") + 228 at remap.cpp:321
    frame #17: 0x000000010e209c97 radiant.bin`CModelWrapper::construct(this=0x00007fa8496407e0) + 135 at pluginmanager.cpp:214
    frame #18: 0x000000010e209b5d radiant.bin`CModelWrapper::CModelWrapper(this=0x00007fa8496407e0, id="models/weapons/machinegun/tris.obj", version="obj") + 109 at pluginmanager.cpp:192
    frame #19: 0x000000010e209ae5 radiant.bin`CModelWrapper::CModelWrapper(this=0x00007fa8496407e0, id="models/weapons/machinegun/tris.obj", version="obj") + 37 at pluginmanager.cpp:190
    frame #20: 0x000000010e20984d radiant.bin`CModelManager::GetByID(this=0x000000010e2c7700, id="models/weapons/machinegun/tris.obj", version="obj") + 237 at pluginmanager.cpp:278
    frame #21: 0x0000000110230413 entity.so`CEntityEclassModel::SetName(this=0x00007fa849641ef0, name="models/weapons/machinegun/tris.obj") + 419 at eclassmodel.cpp:133
    frame #22: 0x0000000110231ab6 entity.so`Entity_UpdateClass(e=0x00007fa8496420f0, value="weapon_machinegun") + 822 at entity_entitymodel.cpp:71
    frame #23: 0x0000000110230e08 entity.so`Entity_OnKeyValueChanged(e=0x00007fa8496420f0, key="classname", value="weapon_machinegun") + 88 at entity.cpp:347
    frame #24: 0x0000000110231142 entity.so`SetKeyValue(ent=0x00007fa8496420f0, key="classname", value="weapon_machinegun") + 178 at entity.cpp:177
    frame #25: 0x0000000110542f0b map.so`Entity_Parse(pEntity=0x00007fa8496420f0) + 347 at parse.cpp:574
    frame #26: 0x00000001105430d5 map.so`Map_Read(in=0x00007fff51a9bfb0, map=0x00007fff51a9bf38) + 277 at parse.cpp:605
    frame #27: 0x000000011054338a map.so`Map_ReadQ2(in=0x00007fff51a9bfb0, map=0x00007fff51a9bf38) + 42 at parse.cpp:652
    frame #28: 0x000000010e1fc3a2 radiant.bin`CSynapseClientRadiant::ImportMap(this=0x00007fa847416f90, in=0x00007fff51a9bfb0, ents=0x00007fff51a9bf38, type="map") + 66 at pluginmanager.cpp:452
    frame #29: 0x000000010e1f240d radiant.bin`Map_Import(in=0x00007fff51a9bfb0, type="map", bAddSelected=false) + 77 at map.cpp:517
    frame #30: 0x000000010e1f25aa radiant.bin`Map_LoadFile(filename="/Users/jdolan/.quetoo/default/maps/darkzone.map") + 282 at map.cpp:566
    frame #31: 0x000000010e243d5d radiant.bin`MRU_Activate(index=1) + 77 at qe3.cpp:1449
    frame #32: 0x000000010e1d2660 radiant.bin`MainFrame::OnMru(this=0x00007fa847416c40, nID=57617) + 48 at mainframe.cpp:4451
    frame #33: 0x000000010e1cf59a radiant.bin`HandleCommand(widget=0x00007fa84981a660, data=0x000000000000e111) + 186 at mainframe.cpp:407
```

Steps to reproduce:

1. Load a map that references an `.obj` model.

-or-

1. Attempt to place an `.obj` model via the entity inspector.

I looked into this briefly, and at first glance, I'm not sure what's wrong. For my particular use case, I'm dealing with `.obj` models loaded from the filesystem directly (not in `.pk3` or `.pak` archives).

The buffer is loaded successfully, as I confirmed in the debugger:

```
(lldb) p (char *) buffer
(char *) $0 = 0x00007fc67e0f4000 "# Blender v2.69 (sub 0) OBJ File: 'model.blend'\n# www.blender.org\nmtllib tris.mtl\no model\nv 6.000000 24.225451 0.589006\nv 6.000000 23.937920 1.088342\nv 6.000000 23.507599 1.421987\nv 6.000000 23.000000 1.539148\nv 7.600000 18.499809 0.589006\nv 7.700000 18.878611 1.088342\nv 7.800000 19.445526 1.421987\nv 7.800000 21.714249 1.539148\nv 6.000000 23.000000 1.200000\nv 6.000000 23.700001 1.000000\nv 14.395568 23.000000 1.200000\nv 14.675569 23.700001 1.000000\nv -2.500000 24.225451 0.589006\nv -2.500000 23.937920 1.088342\nv -2.500000 23.507599 1.421987\nv -2.500000 23.000000 1.539148\nv 4.480000 18.439810 0.589006\nv 4.400000 18.878611 1.088342\nv 4.000000 20.245525 1.421987\nv 3.000000 21.614246 1.539148\nv 13.995568 22.000000 1.200000\nv 20.500000 21.000000 1.200000\nv 20.500000 20.000000 0.725694\nv 20.199999 18.400000 0.725694\nv 18.799999 13.900000 0.564429\nv 16.500000 14.599999 0.564429\nv 17.699999 19.100000 0.725694\nv 17.299999 20.400000 0.967593\nv 18.499998 19.200001 1.400000\nv 15.299999 20.400000 0.960000\nv 17.299999 14.89"
```

I see that `vfsLoadFile` and `vfsFreeFile` use `g_malloc` and `g_free` respectively, so the crash isn't immediately clear.

The model file in question is here:
https://raw.githubusercontent.com/jdolan/quetoo-data/master/target/default/models/weapons/machinegun/tris.obj

I don't have a workaround for this right now. I'm reverting to a pre-Picomodel revision in order to map for Quetoo :(

### PR DESCRIPTION
**Pull request by Mateos81**
Was due to trying to free twice the same buffer. Fixes #395.

### CODE REVIEW

**Comment by Pan7** [comment]
Probably its better to set `buffer = NULL;` here
https://github.com/TTimo/GtkRadiant/blob/master/libs/picomodel/picointernal.c#L207
and
https://github.com/TTimo/GtkRadiant/blob/master/libs/picomodel/picointernal.c#L211

**Comment by Mateos81** [comment]
Yeah, that would make if (buffer) {} return false; I'd like to know why it crashes with 1.6 code though, while for 1.5/Net I guess it doesn't (I'll have to try importing an OBJ in them first to be sure).

**Comment by Mateos81** [comment]
It did not help fyi; thought I posted this here, but no ^^' Probably explains why this is still opened.

**Comment by jdolan** [comment]
This PR addresses 1/2 of the crashes. @Pan7 submitted 2 PR's that fully resolve the issue, and those have been merged. I think it makes sense to close this PR out?

**Comment by Mateos81** [comment]
Thank you @Pan7 and @jdolan, sorry for all the trouble ^^'

**Pull request closed without merging**
