### PR TITLE
initial unvanquished support

### PR DESCRIPTION
**Pull request by illwieckz**
Hi these are the first stones in the wall of Unvanquished support. Well, I was bored to continuously going through insane conflicting issues everytime I wanted to rebase code on master branch, having to hardcode game is painful, and the way it's hardcoded is very painful. So, I'm bored to solve rebase conflict issues, hence this PR.

This code is based on historical @neumond's code. I removed his pk3dir support code from his commits, but except that, they are them. I also squashed some commits that were just removing or modifying code from previous commits.

After that I added some fixes because some paths changed for example, or did some whitespace bikeshedding on q3map2 game file to reduce diff noise with NetRadiant tree.

### CODE REVIEW

**Comment by illwieckz** [comment]
That code is able to load current unvanquished assets, and also load the assets from master branches from [assets repositories](https://github.com/UnvanquishedAssets/UnvanquishedAssets) when merged atop the _pk3dir/dpkdir_ branch (#533), but sometime it's going through some issues that does not looks like to be related to this PR.

For example I'm not able to load the _parpax_ map, GtkRadiant is going through `.map` format mismatch, q3map2 too.

The recently introduced texture browser only displays the directories that really exists, not directories for shader path only. Unvanquished uses for example `textures/shared_trak5/floor2e` shader path but `textures/shared_trak5_src/floor2e_d.png` for diffuse map file, and current GtkRadiant only displays the `textures/shared_trak5_src` directory and not the `textures/shared_trak5` one. It's probably a bug from the current shader code and is probably unrelated to this PR.

Note that if Unvanquished support is added to q3map2 and I was able to compile a map (I only tried the [_vega_ map](http://github.com/IngarKCT/map-vega) on _bsp_ stage though), it's heavily not recommended to compile Unvanquished maps with GtkRadiant's q3map2 because it lacks too much features, just compare [this](https://github.com/illwieckz/GtkRadiant/blob/unvanquished/tools/quake3/q3map2/game_unvanquished.h#L61-L79) to [this](https://gitlab.com/xonotic/netradiant/blob/master/tools/quake3/q3map2/game_unvanquished.h#L61-98) and cry… :cry:

**Comment by TTimo** [comment]
I kinda want to look at all those Unvanquished related commits for 1.6.6 once we have something reasonably stable and reliable for 1.6.5 to move on from.

**Comment by illwieckz** [comment]
Note that you must delete `site.sconf` to be able to fetch the Unvanquished gamepack (probably a bug, scons it's loading the old gamepack list from this file even if `config.py` was edited to add new gamepacks).

**Comment by illwieckz** [comment]
there is no urge to merge that until #533 is merged (pk3dir support) and #573 is fixed (multiple shaderlist.txt issue)

**Pull request merged**
