### PR TITLE
Increase MAX_MAP_VISIBILITY as certain QuakeLive maps are starting to hi...

### PR DESCRIPTION
**Pull request by QBall147**
...t the limit

### CODE REVIEW

**Comment by TTimo** [comment]
Wouldn't that require a new BSP version?

**Comment by jdolan** [comment]
Yea, I think it would. I had to increase this limit in Quetoo. The limit that was set is somewhat arbitrary (it's not `UINT16_MAX`, for example), but increasing it would likely require small changes in cm_model.c.

**Comment by ensiform** [comment]
The variable isn't actually referenced in idTech3, it only exists in qfiles.h as a define.

**Comment by TTimo** [comment]
bspVisBytes array will get bigger, AddLump LUMP_VISIBILITY may end up writing a larger lump than the old max value of MAX_MAP_VISIBILITY

so that won't break backwards compatibility, if an engine isn't prepared for loading a map with a larger vis value it will choke on those new maps but whatever. merging!

**Comment by ensiform** [comment]
The engines have the definition in qfiles.h but don't actually check it iirc.  I wouldn't go beyond 31/32 bits though just in case.

**Pull request merged**
