### PR TITLE
Texture directory list

### PR DESCRIPTION
**Pull request by Pan7**

### CODE REVIEW

**Comment by Pan7** [comment]
Adds a texture directory list on the left side of the texture images.
Moves the textures directories in the menu to a separate sub menu.
Might have to reorder where to load the texture directories for both.

**Comment by jdolan** [comment]
✨ 💯 ✨

**Comment by Mateos81** [comment]
@Pan7 Conflicts!
@TTimo Perhaps discussed at some point on IRC but missed it: what has prevented this from being merge before?

**Comment by TTimo** [comment]
I was hoping to test it out and see what it did before merging it in, but that's not really happening. So let's go ahead and merge this in

**Pull request merged**
