### PR TITLE
GTK3 compatibility

### PR DESCRIPTION
**Pull request by Pan7**
Is it a good idea to add GTK3 compatibility like this?

### CODE REVIEW

**Comment by Garux** [comment]
Why not.
Does it run bugles with gtk3 then?

**Comment by TTimo** [comment]
@Pan7 - so we would link and use gtk3 by default on GNU/Linux and Mac? But stay with gtk2 on Windows for now? The GL widget problem we are having is only on Windows+gtk3, is it?

My only concern there is introducing Windows only issues due to it being the only platform that would still be on gtk2?

**Comment by Pan7** [comment]
When i started with the gtk3 branch i didn't realise that radiant is using really old GTK code.
Slowly updating it to GTK2.
GTK3 shouldn't be that much changes.
Right now the GTK3 stuff works only with my custom gtkglext https://github.com/Pan7/gtkglext on windows because GTK3 has overlapping function names with gtkglext.
gtkglext isn't supported with GTK3.
I suggest not to use GTK3 until it works with gtkglarea.

**Comment by TTimo** [comment]
Ok so even on Linux and Mac, we need to address GL support (issue 382) before we can hope to use gtk3, correct?

**Comment by Pan7** [comment]
Yes, once gtkglarea is working on one platform it should work on the others too.

**Comment by TTimo** [comment]
GtkGLArea and issue #382 not actually necessary for gtk3 - see #299. Closing this pull request, let's coordinate on issue #299 for now.

**Pull request closed without merging**
