### PR TITLE
Option to color detail brushes in 2d views

### LINKED ISSUE #278: Feature Request: Coloured detail brushes in 2D views
Currently, it's a bit hard to distinguish between detail and structural brushes unless you keep hitting the filter keys. It would be useful to have detail brushes show up in the editor's 2D views as a different colour, much like how func_group objects show up blue, or how static meshes show up as orange.

### PR DESCRIPTION
**Pull request by bigjilm**
Adds Detail Brush to the Misc->Colors menu
Closes #278 

(I'm wondering though is #define ID_COLORS_DETAIL 37002 ok? I chose it because ID_COLOR_SETYDNAR is 37001)

### CODE REVIEW

**Comment by bigjilm** [comment]
Sorry, just realized the way I'm doing it overrides other colors, like for triggers and func_groups

**Comment by Mateos81** [comment]
I tried to get into Radiant code and see where the colouring is done but failed, I personally appreciate your pull request for a learning purpose :) I guess you're not far from the solution, just check that the brush is part of the worldspawn (rest being coloured differently) :) It would be cool to find a way to differentiate the func_group's which are structural from the ones being detail, no idea how to do this right :/

**Comment by bigjilm** [comment]
Actually I think this fixes it, but I want to be sure before I make another pull request. https://github.com/bigjilm/GtkRadiant/commit/c55e2601142fd3dbfc3adc2098c307345ed1b0c7

**Comment by Mateos81** [comment]
Nice, thank you :)

**Pull request merged**
