### PR TITLE
Reduce difference with netradiant

### PR DESCRIPTION
**Pull request by uis246**
Also I'd like to remove `tools/quake2/qdata_heretic2/common/mathlib.h` both here and in NR. Should I make it separate PR or put it here too?

### CODE REVIEW

**Comment by TTimo** [comment]
Thanks, but there is no way we'll review all this to merge it in. We are also not looking to essentially merge netradiant into the gtkradiant codebase.

If you are wondering what kind of contributions might be appropriate for the project, please have a read through our mission statement on https://icculus.org/gtkradiant/

**Comment by uis246** [comment]
Oops

**Comment by uis246** [comment]
Sorry, it seems I pushed wrong branch

**Comment by uis246** [comment]
PR of shame. No idea how this happened.

**Pull request closed without merging**
